Filter standuper list
yoyrandao/standup-watcher pull request #2
Opened 2021-08-22 16:21 UTC by BigFinger494

Добавил отслеживание любимых стендаперов

2021-08-23 19:19 UTC, yoyrandao requested changes
Я понял, почему конфликт большой такой - у тебя пробелы везде,  а у меня табы. Либо поправь сам, либо вольем так, я сам потом прожимать везде форматтинг буду. Вообще норм, но у меня пара вопросов есть. Например как чел узнает, кто у него уже в фильтрах. А остальное просто импрувы того, что уже есть + пара багов на глаз

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Processing/Notifying/BotFacade.cs
> +                        requestedAuthor = requestedAuthor.Skip(1).ToList();
Лучше сплитануть по команде и тримануть первый элемент от получившегося, будет читаемее.

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Startup.cs
> +				options => options.UseNpgsql(connStr));
Это можно вернуть, как было.

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Processing/Notifying/BotFacade.cs
> +            _subscribedAuthors = subscribedAuthors;
_subscribedAuthors**Repository**

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Processing/Notifying/BotFacade.cs
> +            return author;
1. Можно вернуть сразу new, без лишней переменной
2. Метод наверное стоит переименовать а-ля CreateNewAuthorFilter или что-то типа того
3. Static
4. Смотри, CreationTimestamp и ModificationTimestamp нужны для легкого определения, когда и во сколько что-либо было сделано. Если запись новая, то эти два поля совпадают, потому что запись не была модифицирована. В твоем случае ModificationTimetamp > CreationTimestamp. Когда кто-либо в будущем будет смотреть в бд и диагностировать что-то, он может подумать, что запись поменялась (даже не учитывая, что в нашем проекте нет функционала по апдейту всего этого дела). В общем лучше вынести Datetime.Now в отдельную переменную и ее уже гнать в БД.

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Processing/Notifying/BotFacade.cs
> +                ,
А как чувак узнает, на кого у него сейчас фильтр стоит?

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Processing/Notifying/BotFacade.cs
> +                            var subscribed = searchedAuthors.First();
.FirstOrDefault(), затем проверка на нулл. Нечего лишний раз в бд холостыми запросами плеваться

2021-08-23 19:19 UTC, yoyrandao commented on src/StandupWatcher/Workers/NotificationWorker.cs
> +					var filteredNotifications = payload.Where(regularEvent => subscribedAuthors.Any(authors => regularEvent.Artist.Contains(authors.StanduperName)));
Если у человека нет фильтров, то ему придет ничего

2021-08-27 09:03 UTC, yoyrandao requested changes

2021-08-27 09:03 UTC, yoyrandao commented on src/StandupWatcher/DataAccess/Models/SubscribedAuthors.cs
> +    public record SubscribedAuthors : Entity
Если добавил сюда таблицу добавить ее и в скрипт деплоя

2021-08-28 16:26 UTC, BigFinger494 commented on src/StandupWatcher/Processing/Notifying/BotFacade.cs
> +                            var subscribed = searchedAuthors.First();
лишнее

2021-09-27 19:51 UTC, merged